### ISSUE TITLE
Upload-Funktion (immer nur eine Datei?)

### ISSUE THREAD

**Issue by Natenom** [openbikesensor/OpenBikeSensorFirmware#102]
Beim Klick auf Upload wurde bladatei3.csv hochgeladen. Dann habe ich nochmal drauf geklickt und es wurde bladatei4.csv hochgeladen.

Sollten nicht alle Dateien auf einmal hochgeladen werden?

**Comment by boldt** [comment]
@uwewoessner

**Comment by Natenom** [comment]
Beim nächsten Test wurden von vier nur drei Dateien hochgeladen, wobei von den dreien online nur eine angezeigt wird.

**Comment by amandel** [comment]
A lot has changed here. Code tries to upload all files and also continues after one file got an error.
