### ISSUE TITLE
Verschieben in /upload funktioniert nicht, wenn Dateien schon vorhanden

### ISSUE THREAD

**Issue by Natenom** [openbikesensor/OpenBikeSensorFirmware#113]
Normalerweise läuft man nicht in diesen Fall rein, wenn man die Daten nur per WLAN hochlädt. Ich habe aktuell die Daten per SD-Karte ausgelesen und dabei auch die Datei tracknumber.txt gelöscht.

D. h. die erste Datei fängt wieder bei sensorData1.txt an.

So eine gibt es aber schon in /upload.

Lädt man jetzt die Daten hoch, dann passiert magic und man kann beliebig oft dieselben Daten hochladen.

**Comment by boldt** [comment]
@uwewoessner

**Comment by amandel** [comment]
This leads to multiple uploads of the same track - because the file is not deleted from the OBS and uploaded again in the next Upload.
Idea would be to try different naming in the target Folder in that case (add a .1, .2 ...)

**Comment by uwewoessner** [comment]
duplicate names should not occur in the current version. If it still happens this should be fixed.
