### ISSUE TITLE
Möglichkeit, die Tracks herunterzuladen

### ISSUE THREAD

**Issue by Natenom** [openbikesensor/OpenBikeSensorFirmware#115]
Vielleicht ein Untermenü mit Liste aller Dateien im / der SD-Karte, die man dann (erstmal) einzeln herunterladen kann?

Mögliche Fälle:
* Nicht jeder möchte das Gerät in sein WLAN lassen.
* Man möchte vielleicht mal unterwegs ohne Zugriff aufs WLAN die Daten sehen.

**Comment by opatut** [comment]
Das geht jetzt. Allerdings nur, wenn du per WLAN mit dem OBS verbunden bist. Das reicht aber, wenn das der unterwegs-hotspot ist, den der OBS aufmacht, wenn er dein Zu-Hause-WLAN nicht findet.
