### ISSUE TITLE
Feedback, wenn keine Daten zum Upload da sind

### ISSUE THREAD

**Issue by Natenom** [openbikesensor/OpenBikeSensorFirmware#116]
Wenn keine Tracks im / der SD-Karte sind und man auf "Upload tracks" klickt, kommt nur die Unterseite. Hier könnte man entweder die Info zeigen, dass es keine Tracks für den Upload gab oder man "graut" direkt im Hauptmenü den Punkt "Upload tracks" aus.

**Comment by amandel** [comment]
Fixed with #191
