### ISSUE TITLE
Wifi: connection fails sometimes

### ISSUE THREAD

**Issue by boldt** [openbikesensor/OpenBikeSensorFirmware#120]
idea:
- if connection failed
- diconnect
- sleep
- connect again

https://github.com/espressif/arduino-esp32/issues/2501

**Comment by amandel** [comment]
-> we should retry after a `[W][WiFiGeneric.cpp:353] _eventCallback(): Reason: 202 - AUTH_FAIL` error (at least this is what I see as error in that case.)
