### ISSUE TITLE
Deletion of single tracks through the web interface

### ISSUE THREAD

**Issue by Natenom** [openbikesensor/OpenBikeSensorFirmware#163]

**Comment by opatut** [comment]
![image](https://user-images.githubusercontent.com/235784/101776744-b568b680-3af1-11eb-9b23-38cd5d6f0f1f.png)

There is this button in the track details page, if you are the owner of the track. Do you need anything else?

**Comment by amandel** [comment]
@Natenom  - I assume you want to delete from SD card? Otherwise we can close?

**Comment by Natenom** [comment]
Jups, from SD card via the interface on the OBS.

**Comment by jhartmannwf** [comment]
even deletion of whole contents i.e. after a test phase, would be nice

**Comment by amandel** [comment]
@jhartmannwf  -  that is in #175 / #111
