### ISSUE TITLE
Change in Config-Menu

### ISSUE THREAD

**Issue by mega-stoffel** [openbikesensor/OpenBikeSensorFirmware#167]
The "Upload Tracks" is in the chapter "Maintenance".
I'd say it's not a maintenance-task, but would prefer to create an own chapter "Upload" (or even a better name? Suggestions welcome). And, because it's probably the most used function in the near future, put it on the first place of the config menue.

**Comment by amandel** [comment]
"Upload Tracks" is somehow international known. What about "Publish Tracks"?

**Comment by mega-stoffel** [comment]
well, technically it might not be a publishing step, as long as you don't set the "visible" option.
