### ISSUE TITLE
Add "format SD card" button

### ISSUE THREAD

**Issue by opatut** [openbikesensor/OpenBikeSensorFirmware#175]
I'd like to be able to format the SD card through the config server. This may help if you haven't formatted the SD card as fat32 (or whatever is required), and also when handing out your device to other people.

**Comment by opatut** [comment]
Related to #111. I want to be able to format the SD card independent of a factory reset.

**Comment by amandel** [comment]
Looks like the SD library used by as and by default in the Arduino framework does not support formatting of SD Cards, we could either
1. delete file by file
2. use a different lib like https://github.com/greiman/SdFat (we should migrate all SD card code to this lib then)
