### ISSUE TITLE
Falsche Anzahl in privacyConfig (immer 10)

### ISSUE THREAD

**Issue by Natenom** [openbikesensor/OpenBikeSensorFirmware#179]
Egal wie viele Privacy Zones ich einstelle, ob 12 oder 1, der Wert von "privacyConfig" in der exportierten json-Datei ist immer 10.

**Comment by opatut** [comment]
`privacyConfig` ist not the number of areas but a bitmask describing how to behave inside privacy areas:

```cpp
enum PrivacyOptions {
  AbsolutePrivacy = 0x01, //1
  NoPosition = 0x02, //2
  NoPrivacy = 0x04, //4
  OverridePrivacy = 0x08 //8
};
```

The value of 10 (if decimal) is therefore 8+2 = `OverridePrivacy & NoPosition`.
