### ISSUE TITLE
Report of Time and number of sattelites does collide

### ISSUE THREAD

**Issue by Halbelunge** [openbikesensor/OpenBikeSensorFirmware#205]
This was introduced somewhen in the main.

 else {
      char timeStr[32];
      snprintf(timeStr, sizeof(timeStr), "%02d:%02d:%02d %dsa",
               gps.time.hour(), gps.time.minute(), gps.time.second(), gps.satellites.value());
      satellitesString = String(timeStr);
    }
    displayTest->showTextOnGrid(2, 5, satellitesString,DEFAULT_FONT);
    
 The problem is, that if a time is there, but 0 sattelites, the time is displayed but the number of satellites are out of bounds.
 there Should be a check, or everyhing should scroll 1 row up.

**Comment by amandel** [comment]
Not sure where you see the collision? Display of time is by intention - the time is displayed while waiting for satellite reception.

**Comment by Halbelunge** [comment]
cant get GPS signal at the moment, so I cant provide a picture of the dispaly contents

bit it trys to display xx:xx:xx 0 sats but can only display xx:xx:xx 0 sa 
and the a of sa is only displayed half.

I have (for now) implemented a small auto scrolling that scrolls all lines one up, the moment a time is found.
So the following is shown.

xx:xx:xx
0 / 4 sats

instead of 
xx:xx:xx 0 sats

**Comment by Halbelunge** [comment]
This collides ith your pull request Andreas :/

I try to get a picture of what is the problem

**Comment by Halbelunge** [comment]
![20210109_222958](https://user-images.githubusercontent.com/12426445/104109056-581b7d00-52ca-11eb-8418-9950e24651c9.jpg)
This is what I talk about

**Comment by amandel** [comment]
Actually we could overwrite or skip the csv line. The actual file is not written at that point, just some buffers are prepared in memory. So this can hardly fail and it gives no real information. 
Then we can print something like
'0 Satellites' in the 2nd line below the time.

**Comment by amandel** [comment]
@Halbelunge should be OK with the new release
