### ISSUE TITLE
Be sure to mention all possible ways of flashing the sensor.

### ISSUE THREAD

**Issue by tobst** [openbikesensor/OpenBikeSensorFirmware#21]
So far, flashing via USB from the Arduino IDE, OTA over the Arduino IDE, and Uploading the binary over the sensor's webserver is implemented.

**Comment by amandel** [comment]
Here is a documentation via the flash tool provided by espressif: https://github.com/openbikesensor/OpenBikeSensorFirmware/blob/master/docs/software/firmware/initial_flash.md

**Comment by amandel** [comment]
Flashing / installation is now possible via https://install.openbikesensor.org/ no platform specific setup is needed any more. So I close this.
