### ISSUE TITLE
Privacy Area should be defined as irregelar polygon instead of circle

### ISSUE THREAD

**Issue by stberg-os** [openbikesensor/OpenBikeSensorFirmware#216]
If the privacy area is defined by center and radius it still allows guessing the center point of the privacy area by viewing all tracks of a user.

If the privacy area is an irregular polygon as shown in the image, it's impossible to guess the actual point. THe Screenshot is taken from komoot.
![image](https://user-images.githubusercontent.com/77753804/105233761-95092e80-5b6a-11eb-8bb7-b7ad1125d3ab.png)

**Comment by amandel** [comment]
The filtering of the privacy area does not happen on the center of the circle. Instead as @mega-stoffel  explained the circle is shifted by a random offset. If there is no strong need I would *not* add additional complexity to this, neither on the software nor on the user / usage side. There is a more sophisticated filter possibility planned on the portal side, see https://www.openbikesensor.org/user-guide/privacy-zones.html

**Comment by amandel** [comment]
Closing for now as described above.
