### ISSUE TITLE
I want to be able to inject a initial configuration via sd card content

### ISSUE THREAD

**Issue by amandel** [openbikesensor/OpenBikeSensorFirmware#217]
1) Check SD card for a `obs.json` file on startup
2) If such a file exists, read the config from that file and store the config on SPIFFS / ObsConfig::CONFIG_FILENAME overwrite existing data
3) delete the `obs.json` from the SD card.

Format of the  `obs.json` is the *internal* https://github.com/openbikesensor/OpenBikeSensorFirmware/blob/feature/gps/docs/software/firmware/obs_cfg.md

To just set the Wifi credentials the file would look like:
```json
{
    "obs":[
        {
            "wifiPassword":"swordfish",
            "wifiSsid":"obs-cloud"
        }
    ]
}
```

**Comment by Steffeng5** [comment]
If possible: Use all parameters from internal obs.json. If Parameter is present: overwrite. But if possible: no need to add all possible parameters.
