### ISSUE TITLE
GPS debug/optimization mode

### ISSUE THREAD

**Issue by tobst** [openbikesensor/OpenBikeSensorFirmware#218]
When different mount positions become available it would be nice to have live feedback on gps quality when moving the sensor around. Currently, this can be done by entering config mode a refreshing "about page". Additionally, helpful gps stats could be shown on the display in a GPS optimization mode. Which are the values to look at? Number of satellites? HDOP? Anything else?

**Comment by amandel** [comment]
Check out #213 to see the values exposed by the different posibilities

**Comment by amandel** [comment]
@tobst  - while waiting for GPS the _SNR_ is now shown. It gives a bit of a information of the GPS reception quality. From what I see from the manual this is the best we can do with the information from the device. Feel free to re-open if we should display or collect other data.
