### ISSUE TITLE
please extend time for displaying "ALP Data up to date"

### ISSUE THREAD

**Issue by Ventusfahrer** [openbikesensor/OpenBikeSensorFirmware#284]
When loading ALP Data after successfully connecting to WLAN "ALP Data ..." is visible on the display.
After the data is successfully loaded from the internet you print out "ALP Data up to date" very, very shortly. 

Without taking a video you (or at least I) can't read the message.
Please give us a little more time (1-2 seconds) to read this information.

Thanks

**Comment by boldt** [comment]
@see: https://github.com/openbikesensor/OpenBikeSensorFirmware/pull/314
