### ISSUE TITLE
Missing on how to build the firmware

### ISSUE THREAD

**Issue by tfar** [openbikesensor/OpenBikeSensorFirmware#304]
How do you build the firmware and then deploy/flash it on the ESP32 after checking out the repo? Should this be part of the README?

**Comment by boldt** [comment]
It is part of our official central documentation:

https://www.openbikesensor.org/docs/firmware/#installation--flashen

**Comment by tfar** [comment]
Yup. I was missing the bits #302 links to . Ta.
