### ISSUE TITLE
wrong millis() definition?

### ISSUE THREAD

**Issue by MegaC-C** [openbikesensor/OpenBikeSensorFirmware#319]
https://github.com/openbikesensor/OpenBikeSensorFirmware/blob/dde6fc2529682695b80500a45b22536094a2379d/src/OpenBikeSensorFirmware.cpp#L82

from esp_timer.h :
int64_t esp_timer_get_time(void);
...
 *@return Timestamp of the nearest timer event, in microseconds.

perhaps i have missed a *1000, but it seems as if micros() are compared to millis()?

**Comment by amandel** [comment]
Thanks for that catch - the initial value is not used but for sure this is not correct.
