### ISSUE TITLE
Enable multiple APs for upload

### ISSUE THREAD

**Issue by gluap** [openbikesensor/OpenBikeSensorFirmware#339]
Initiatives offering OBS for borrowing often offer them pre-configured with the initiative (ADFC, Makerspace) WIFI. Users would like to add their personal wifi to enable uploading from home. 

[On the forum the possibility to have a second wifi configured in the OpenBikeSensor was discussed.](https://forum.openbikesensor.org/t/waeren-2-wlan-im-obs-moeglich/1600/5)

There is already a workaround though: Most of the time the password of the Initiative wifi is public, and users can simply open a hotsppot on their mobile to mimic that wifi and upload via the hotspot. (or configure a guest wifi on their home router).

**Comment by amandel** [comment]
Implemented with #335 - available with [v0.19.877](https://github.com/openbikesensor/OpenBikeSensorFirmware/releases/tag/v0.19.877)
