### ISSUE TITLE
Generate a user documentation

### ISSUE THREAD

**Issue by boldt** [openbikesensor/OpenBikeSensorFirmware#49]

**Comment by boldt** [comment]
https://github.com/Friends-of-OpenBikeSensor/OpenBikeSensorFirmware/wiki/User-Guide

**Comment by 4n08o** [comment]
Close this?

**Comment by boldt** [comment]
We still need to improve it!

**Comment by amandel** [comment]
Link is https://www.openbikesensor.org/user-guide/ 

Should we close this and track the documentation issues with the documentation repository?
