### ISSUE TITLE
BatteryLevel

### ISSUE THREAD

**Issue by boldt** [openbikesensor/OpenBikeSensorFirmware#54]
* [ ] Get value from ESP
* [ ] "Show battery" option in config
* [ ] Show battery on display

**Comment by 4n08o** [comment]
As we (may) have a dependency to the issue #27 there is real benefit here.

**Comment by amandel** [comment]
I started as [VoltageMeter](https://github.com/Friends-of-OpenBikeSensor/OpenBikeSensorFirmware/blob/feature/new-cvs-format/OpenBikeSensorFirmware/VoltageMeter.cpp) class in #146 - currently only for csv and "debugging" option on the display, but for sure can be extended. Might be also in relation with #137

**Comment by amandel** [comment]
@Halbelunge  - can we bring the `get_batterie_percent` logic into ``VoltageMeter::readPercentage`` and so make `battery.cpp` / `battery.h` obsolete again?
