### ISSUE TITLE
add meaningfull filenames

### ISSUE THREAD

**Issue by tobst** [openbikesensor/OpenBikeSensorFirmware#6]
They are called sensorDataXXX.csv with incrementing numbers, but should contain some useful metadata in the file

**Comment by 4n08o** [comment]
Proposal: 
use the sensor identifier and an numerical increment.
(nice would be a timestamp, e. g. UTC, but this requires working GPS at the time of writing.

**Comment by amandel** [comment]
The file includes now some (encoded) metadata information in the very 1st line as described at https://github.com/openbikesensor/OpenBikeSensorFirmware/blob/master/docs/software/firmware/csv_format.md - feel free to reopen or open a new issue if this is not sufficient.
