### ISSUE TITLE
Detect empty files

### ISSUE THREAD

**Issue by boldt** [openbikesensor/OpenBikeSensorFirmware#62]
On boot, detect empty files and use them

> Viele Dateien sind 63 Byte groß (keine Daten, nur Header von CSV)

**Comment by amandel** [comment]
We also have the demand to rename the file once we have a valid time -> `2020-17-07T16.00.00-AAAA.obstrack.csv` <- I have to think if we calculate the time back to the beginning of the track, AAAA would be the device id. Related to #95 and #113 

There is no need to write the file when we create the header, we could just fill the buffer and so never create files that only contain header data.

**Comment by mega-stoffel** [comment]
Please don't use something like 2020-17-07, that's not useful at all. I'd prefer (in this case) 2020-07-17.

**Comment by amandel** [comment]
Sure
