### ISSUE TITLE
SD-Library

### ISSUE THREAD

**Issue by boldt** [openbikesensor/OpenBikeSensorFirmware#66]
SD-Libs vergleichen und testen:

* https://github.com/arduino-libraries/SD
* https://github.com/greiman/SdFat
* https://github.com/espressif/arduino-esp32/tree/master/libraries/SD

> Ich würde es mit der SDFAT oder der von Arduino probieren, nicht mit der Expressif.

**Comment by amandel** [comment]
Is this still to be decided and replace the currently used lib or is this one stale? There might be some prior discussion I do not know.
