### ISSUE TITLE
Right Sensor

### ISSUE THREAD

**Issue by boldt** [openbikesensor/OpenBikeSensorFirmware#67]
> Rechts wurden sehr häufig Werte angezeigt, obwohl erst ca. 5 m bis zum Waldrand waren. Gras war nicht ansatzweise hoch genug für den Sensor

**Comment by 4n08o** [comment]
I see a similar issue if I lean the bike a few degrees to the right.
Is the direction of the ultra sonic sensor wrong/broken or the mounting of the OBS itself?  How can this be evaluated by the user?

**Comment by amandel** [comment]
This one seems to be stale? We had long discussions on general sensor readings, not limited to the sensor in one direction. I vote to colse this.
