### ISSUE TITLE
complete privacy areas

### ISSUE THREAD

**Issue by tobst** [openbikesensor/OpenBikeSensorFirmware#68]
Added with eab461171e3a5105e2186e591b276dbcf593dd30 :
- save and load privacy aread in config file
- calculate distance from privacy point
- set bool isInsidePrivacyArea and write to csv

Still Missing:
- [x] enter coordinates and radius in the webserver
- [x] button "make current gps location private" in webserver
- [x] let user chose and handle decision what to do (just mark in csv, omit location in set, skip whole set)

**Comment by tobst** [comment]
- [ ] remove privacy point from config

**Comment by tobst** [comment]
- [ ] make radius variable when clicking "make current location private"

**Comment by amandel** [comment]
This seems to be very compleat? Can we close it?
