### ISSUE TITLE
Handle button in a separate class

### ISSUE THREAD

**Issue by boldt** [openbikesensor/OpenBikeSensorFirmware#72]
Handle:

* single click
* double click
* long click

**Comment by boldt** [comment]
Discussions:

* https://forum.arduino.cc/index.php?topic=14479.0
* https://forum.arduino.cc/index.php?topic=425587.0
* https://stackoverflow.com/questions/32811098/arduino-click-double-click-and-hold-button
    * Debounce !!
    * https://www.arduino.cc/en/Tutorial/Debounce

Libs:

* https://github.com/poelstra/arduino-multi-button
* http://www.mathertel.de/Arduino/OneButtonLibrary.aspx
    * Works with ticks
* https://playground.arduino.cc/Code/Button/

**Comment by boldt** [comment]
# Buttons and interrupts

* https://www.arduino.cc/reference/de/language/functions/external-interrupts/attachinterrupt/
* https://www.mikrocontroller.net/articles/Verwendung_von_Interrupts_mit_Arduino
* http://diwo.bq.com/de/interrupts-mit-arduino-benutzen/
* https://lastminuteengineers.com/handling-esp32-gpio-interrupts-tutorial/#attaching-interrupt-to-a-gpio-pin

# Libs with Interrupts

* https://github.com/Alarm-Siren/arduino-buttons
* https://github.com/blackketter/Switch
* https://github.com/t3db0t/Button
* https://www.instructables.com/id/Arduino-Push-Switch-Debouncing-Interrupts/

**Comment by Halbelunge** [comment]
Die Lib hier könnte auch passen
[https://github.com/mathertel/OneButton]

**Comment by 4n08o** [comment]
Concept for a button press strategy first?
short press: confirm measurement
long press: enter config?
short double press: cancel measurement (#60)
...?

**Comment by amandel** [comment]
See also #136
