### ISSUE TITLE
Show gps status when making current location private

### ISSUE THREAD

**Issue by mega-stoffel** [openbikesensor/OpenBikeSensorFirmware#75]
auf der Seite, wo man die aktuelle GPS-Position als Privacy-Zone übernehmen kann, wird auf einen GPS-Fix gewartet. Allerdings dauert das eeeeeewig. Da nicht klar ist, ob der Fix tatsächlich nicht da ist, oder ob nur nicht "weitergemacht" wird, sollte der GPS-Status auf diese Seite aufgenommen werden. Ähnlich wie beim Display, z.B. die Anzahl der Satelliten anzeigen und - bestenfalls - dynamisch anpassen; oder mit einem weiteren Knopf "Re-Check GPS Status".

**Comment by boldt** [comment]
Ggf. sollten wir hier einfach auch die GPS-Position des Browsers verwenden, wenn man sich mit einem Hand verbindet.

**Comment by 4n08o** [comment]
Nur wenn GPS-fix da ist, Option Privacy ueberhaupt im Display anbieten sonst ausgrauen oder auf Browser verweisen?

**Comment by boldt** [comment]
Hier sollte man eher regelmäßig mit AJAX such die aktuelle GPS-Position vom Sensor holen, ohne dass man die Seite neu laden muss.

Außerdem sollte die GPS-Position auch manuell eingeben können. Daher ist ausgrauen nicht sinnvoll.

**Comment by amandel** [comment]
See also https://openbikesensor.slack.com/archives/C012H97P10E/p1614247128008000
