### ISSUE TITLE
Webserver not reloaded after position is marked private

### ISSUE THREAD

**Issue by tobst** [openbikesensor/OpenBikeSensorFirmware#77]
`server.on("/makecurrentlocationprivate", HTTP_GET, []()`
should lead to
`    String s = "<meta http-equiv='refresh' content='0; url=/'><a href='/'> Go Back </a>";
    server.send(200, "text/html", s); //Send web page `
when finished, but webserver is not reloaded.

**Comment by boldt** [comment]
We need a JavaScript-/XHR-based version, since the status code cannot be send twice.
