### ISSUE TITLE
Create Developer GitHub pages

### ISSUE THREAD

**Issue by boldt** [openbikesensor/OpenBikeSensorFirmware#82]
* [Github kann das voll automatisch](https://docs.github.com/en/github/working-with-github-pages/setting-up-a-github-pages-site-with-jekyll)
* Nutzt intern [Jekyll](https://jekyllrb.com)
* https://github.blog/2016-12-09-publishing-with-github-pages-now-as-easy-as-1-2-3/
* https://medium.com/@HarryWang/how-to-host-static-markdown-web-pages-using-github-pages-61f80a3a5136

# Ubuntu

* https://jekyllrb.com/docs/installation/ubuntu/
* https://jekyllrb.com/docs/

**Comment by boldt** [comment]
* A new Branch created: [https://github.com/Friends-of-OpenBikeSensor/OpenBikeSensorFirmware/tree/feature/docs](feature/docs)
* Depends on: [https://github.com/Friends-of-OpenBikeSensor/OpenBikeSensorFirmware/tree/feature/platformio](feature/platformio)

**Comment by boldt** [comment]
Theme:

* https://pmarsceill.github.io/just-the-docs/

**Comment by amandel** [comment]
If I do not get it wrong, this was moved to the documentation part?
