### ISSUE TITLE
Check config defaults

### ISSUE THREAD

**Issue by tobst** [openbikesensor/OpenBikeSensorFirmware#90]
Users reported a black screen after gps fix. Is this related to default values in config? If so, make defaults in a way that something is displayed.

**Comment by Halbelunge** [comment]
Yes this is related with the standard configs.

In the 0.1.9-dev this seems to be fixed

**Comment by boldt** [comment]
I guess, we can close this issue

**Comment by amandel** [comment]
Works fine with 0.4.x
