### ISSUE TITLE
If config is broken and button is holded, devices bootloops

### ISSUE THREAD

**Issue by Halbelunge** [openbikesensor/OpenBikeSensorFirmware#92]
If the config has some sort of issue (could not determin what), the device restarts because of an internal panic.

If you hold down the button, it will bootloop. If you release the button, it will start in normal mode.

I will report if this happens again. I will then see if it happens during read of file or after. This should be catched instead of crashing

**Comment by amandel** [comment]
This one seems to be outdated? Can be closed?

**Comment by Halbelunge** [comment]
Maybe this is connected to the low battery bootloop bug!
