### ISSUE TITLE
A lot of critical system functions have just void and no return value

### ISSUE THREAD

**Issue by Halbelunge** [openbikesensor/OpenBikeSensorFirmware#93]
Functions like void FileWriter::appendFile have just void.
They even check inside if something is wrong and then send it out via println().
There should be a return value (best as uint_8t, this just takes 1 byte on the stack) that is 0 if something has gone wrong and 1 if everything is ok.

Every function that calls a function with such a return value should return this value itself. If there is more then one call inside a function the return value should be the logical AND of all calls.

Example

![image](https://user-images.githubusercontent.com/12426445/89118525-8dfc4000-d4a6-11ea-8b69-3e58e177812a.png)

**Comment by amandel** [comment]
I've started to propagate the value to the caller. Still we need a way to show it to the user if such an error occurs - like data can not be written because of a write error or full buffer.

**Comment by amandel** [comment]
Closing this, please create a new one if there is a concrete case. In general checking for return values was improved.
