### ISSUE TITLE
Display tells "CSV ok" without even checking

### ISSUE THREAD

**Issue by Halbelunge** [openbikesensor/OpenBikeSensorFirmware#97]
The Display tells csv read ok, even if it will fail (not regarding bootloop/hardfault).
This is kind of relatet to issue #93 

Here should be a check and this should only be displayed if all of the called functions return 1 (true)!

![image](https://user-images.githubusercontent.com/12426445/89125179-d59dbe80-d4dc-11ea-9d8b-9f2b30482023.png)

**Comment by amandel** [comment]
The SD init is checked now. Since we do only prepare and not write data to the SD in `writer->writeHeader();` this is best we can do for now.
