### ISSUE TITLE
Serial Information tells "wrote data to File" while only wrote to internal databuffer

### ISSUE THREAD

**Issue by Halbelunge** [openbikesensor/OpenBikeSensorFirmware#98]
This code just writes to the internal databuffer that writes somewhen later in the code to the SD card. But in this very moment it writes only to the buffer, the data is not safe on the card yet.

![image](https://user-images.githubusercontent.com/12426445/90936875-70b3f500-e406-11ea-911f-9f313cde336f.png)

**Comment by amandel** [comment]
Text is removed at that place now.
